### ISSUE TITLE
Vite beta-12, TypeError: Cannot read property '__e' of undefined

### ISSUE THREAD

**Issue by wiesson** [JoviDeCroock/prefresh#124]
Error
```
catchError.js:8 Uncaught TypeError: Cannot read property '__e' of undefined
    at catchError.js:8
```

Happens in `catchError.js`
```
import { options } from '/@modules/preact/dist/preact.module.js';
import {
	CATCH_ERROR_OPTION,
	COMPONENT_DIRTY,
	VNODE_COMPONENT
} from '/@modules/@prefresh/core/src/constants.js';

const oldCatchError = options[CATCH_ERROR_OPTION]; // options is undefined here
options[CATCH_ERROR_OPTION] = (error, vnode) => {
	if (vnode[VNODE_COMPONENT] && vnode[VNODE_COMPONENT][COMPONENT_DIRTY]) {
		vnode[VNODE_COMPONENT][COMPONENT_DIRTY] = false;
	}

	if (oldCatchError) oldCatchError(error, vnode);
};
``` 

Somehow it seems that Preact is not imported correctly. 🤷 I have tried to find the reason, but so far without success. Vite has introduced a breaking change in beta-2 that the vite client path has changed from /vite/hmr to /vite/client. Maybe it is related.

**Comment by Grafikart** [comment]
It's not related with path change (I had the same bug before). It happens when I upgrade @prefetch/vite to 0.10.X.
If we rollback to 0.9.0 we loose hotreload but everything work again

**Comment by wiesson** [comment]
I'm not that sure if it is related to prefresh - I have updated vite from 1.0.0-beta.11 and from 1.0.0-beta.12 onwards, the bug occurs

**Comment by JoviDeCroock** [comment]
Everything under 0.10.x is not compatible with the 1.0.0 line of vite, I've contacted people at vite about this since there were no evident breaking changes in `beta.12` so this might be a bug with export mangling, ...

This could also be related to how modules are loaded, ....

**Comment by cdbattags** [comment]
@yyx990803 Any update on this bug? I'm guessing this is definitely due to export mangle?

**Comment by JoviDeCroock** [comment]
This was fixed in `vite@rc.4`

**Comment by wiesson** [comment]
Sorry to ask, but in my case it's still broken - do I need to update the config?

**Comment by JoviDeCroock** [comment]
@wiesson what's broken? I just installed the new vite version and it seemed to work 😅

**Comment by wiesson** [comment]
Hmm, not on my machine 😓 

```
npm init vite-app foo --template preact
cd foo
npm install
npm run dev
```

Updated package.json

```
$ foo cat package.json 
{
  "name": "foo",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "preact": "^10.4.6"
  },
  "devDependencies": {
    "@prefresh/vite": "^0.10.2",
    "vite": "^1.0.0-rc.4"
  }
}
```

Which looks good
```
$ foo npm run dev                            

> foo@0.0.0 dev /Users/wiese/Dev/foo
> vite

vite v1.0.0-rc.4
Port 3000 is in use, trying another one...

  Dev server running at:
  > Local:    http://localhost:3001/
  > Network:  http://192.168.0.80:3001/
```

buuut
<img width="1278" alt="Screenshot 2020-07-31 at 16 37 00" src="https://user-images.githubusercontent.com/933231/89045610-174b2f80-d34c-11ea-8e9f-b9691aaea89f.png">

**Comment by JoviDeCroock** [comment]
Hmm, we should move this issue to vite. It works just fine here 😅 I'll try with a different node verison in abit

**Comment by JoviDeCroock** [comment]
@wiesson I just tried it with my own node v14 and it just works, quite confused at the moment 😅

**Comment by underfin** [comment]
@JoviDeCroock. I notice this issue is fixed by https://github.com/JoviDeCroock/prefresh/commit/42ac94f2020a906c908333810b2386feeb8e6f3f. But install `@prefresh/vite@0.10.2` code is  `@prefresh/vite@0.10.1`.The code (`	path.includes('node_modules') `) is lost.

**Comment by wiesson** [comment]
Thanks @underfin - I can confirm that this fixes the issue 👍

**Comment by JoviDeCroock** [comment]
Good spot, seems like prepublishOnly didn’t run. Hope that’s not a changesets bug 😅
